Develop
whitecolt/airbnb-demo-frontend pull request #1
Opened 2017-11-10 16:56 UTC by whitecolt

Made a markup of a descktop page

2017-11-10 17:00 UTC, evgenyrodionov commented
Название ПРа должно отражать сделанную работу

2017-11-10 17:07 UTC, imevro requested changes

2017-11-10 17:07 UTC, evgenyrodionov commented on public/index.html
> +  <title>React App</title>
смени

2017-11-10 17:07 UTC, evgenyrodionov commented on public/manifest.json
> +  "short_name": "React App",
смени

2017-11-10 17:07 UTC, evgenyrodionov commented on public/index.html
> +  <link rel="stylesheet" href="./normalize.css">
зачем? поставь из нпма

2017-11-10 17:07 UTC, evgenyrodionov commented on public/index.html
> +  <link rel="stylesheet" href="../src/index.css">
зачем? открой `src/index.js`

2017-11-10 17:07 UTC, evgenyrodionov commented on src/App.js
> +import Experiences from "./Experiences/Experiences";
перечитай второй урок про импорты и index.js

2017-11-10 17:07 UTC, evgenyrodionov commented on src/App.js
> +      <div className="Wrapper">
зачем?

2017-11-10 17:07 UTC, evgenyrodionov commented on src/Destinations/Destinations.js
> +      <div className="col-2">
у тебя же фбг2, это что?

2017-11-10 17:07 UTC, evgenyrodionov commented on src/Experiences/Experiences.js
> +import Card from "./ExperiencesCard";
ты и так в Experiences, зачем тебе префикс Experiences?

2017-11-10 17:07 UTC, evgenyrodionov commented on src/Experiences/Experiences.js
> +import { SeeAll, More, Arrow } from "../Homes/Homes";
что это делает в другом модуле вообще? почему оттуда тягаешь?

2017-11-10 17:07 UTC, evgenyrodionov commented on src/Experiences/Experiences.js
> +import arrow from "./Arrow.svg";
почему свг файл назван как компонент?

2017-11-10 17:07 UTC, evgenyrodionov commented on src/Experiences/Experiences.js
> +const Section = styled.div`
мб http://htmlreference.io/element/section ?

2017-11-10 17:07 UTC, evgenyrodionov commented on src/Experiences/Experiences.js
> +const Title = styled.div`
тайтл дивом?

2017-11-10 17:07 UTC, evgenyrodionov commented on src/Experiences/Experiences.js
> +          price={"$50"}
а зачем тут фигурные скобки

2017-11-10 17:07 UTC, evgenyrodionov commented on src/Footer/Footer.js
> +                  <option>Unated States dollar</option>
unated stots dalr

2017-11-10 17:07 UTC, evgenyrodionov commented on src/Header/styled.js
> +export const Header = styled.div`
header — div?

2017-11-10 17:07 UTC, evgenyrodionov commented on src/Header/styled.js
> +export const Input = styled.input`
давай тут тоже див

2017-11-10 17:07 UTC, evgenyrodionov commented on src/Header/styled.js
> +export const MenuLink = styled.a`
тоже дивом давай

2017-11-11 18:16 UTC, imevro requested changes

2017-11-11 18:16 UTC, evgenyrodionov commented on public/index.html
>    <link rel="stylesheet" href="./flexboxgrid2.css">
это зачем тут?

2017-11-11 18:16 UTC, evgenyrodionov commented on public/manifest.json
>    "name": "Create React App Sample",
ну а тут?

2017-11-11 18:16 UTC, evgenyrodionov commented on src/Destinations/Card.js
>      <DestCard>
сделай ссылкой

2017-11-11 18:16 UTC, evgenyrodionov commented on src/Destinations/index.js
> +import Card from "./Card.js";
опусти .джс

2017-11-11 18:16 UTC, evgenyrodionov commented on src/Experiences/index.js
> +import Scroll from "./Card";
это как?

2017-11-11 18:16 UTC, evgenyrodionov commented on src/Experiences/index.js
> +import Scroll from "./Card";
два одинаковых импорта под разными названиями

2017-11-11 18:16 UTC, evgenyrodionov commented on src/Experiences/index.js
> +const Inscription = styled.div`
wtf

2017-11-11 18:16 UTC, evgenyrodionov commented on src/Homes/Card.js
> +import { Stars, Price } from "../Experiences/Card";
Почему ты в Homes импортишь что-то из другого бизнес-модуля?

2017-11-11 18:17 UTC, evgenyrodionov commented
https://github.com/whitecolt/airbnb-demo-frontend/pull/1#issuecomment-343528556

2017-11-12 12:44 UTC, evgenyrodionov commented
Ну и чё с названием ПРа?

2017-11-12 12:46 UTC, imevro requested changes

2017-11-12 12:46 UTC, evgenyrodionov commented on src/index.js
> +import grid from "./grid.css";
не заработает + юзай фбг2

2017-11-12 13:30 UTC, merged

2017-11-12 13:30 UTC, evgenyrodionov commented
Сделай пулл в мастере